import React, { useState } from 'react';
import AppLayout from './components/AppLayout';
import ChatTranscript from './components/ChatTranscript';
import PromptComposer from './components/PromptComposer';
import { Cat, ArrowRight, Zap, Code2, Sparkles, Terminal, ArrowLeft } from 'lucide-react';

export default function App() {
  // START WITH AN EMPTY MESSAGES ARRAY (No initial demo messages)
  const [messages, setMessages] = useState([]);
  const [activeModel, setActiveModel] = useState("GPT-5 Cyber");

  const suggestions = [
    { icon: Code2, title: "Debug React Hooks", desc: "Analyze state sync issues & memory leaks.", tag: "React", prompt: "Help me debug asynchronous React hook re-renders." },
    { icon: Terminal, title: "Tailwind v4 Config", desc: "Explore CSS variables & native @theme directives.", tag: "CSS", prompt: "Explain how to set up theme variables in Tailwind CSS v4." },
    { icon: Sparkles, title: "System Architecture", desc: "Design resilient frontend component boundaries.", tag: "Design", prompt: "What are the best practices for scalable frontend component architecture?" },
    { icon: Zap, title: "Optimize Performance", desc: "Reduce bundle sizes & dynamic re-renders.", tag: "Speed", prompt: "Give me 5 actionable tips to improve Vite + React web application performance." }
  ];

  const handleSendMessage = (text) => {
    const userMsg = {
      id: Date.now(),
      role: 'user',
      content: text,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages(prev => [...prev, userMsg]);

    // Simulated AI response
    setTimeout(() => {
      const aiMsg = {
        id: Date.now() + 1,
        role: 'assistant',
        modelName: activeModel,
        content: `I received your request: "${text}". Here is a clean response generated by ${activeModel}.`,
        codeLanguage: 'javascript',
        codeSnippet: `// Processed output\nconst result = await processTask("${text}");`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setMessages(prev => [...prev, aiMsg]);
    }, 800);
  };

  const handleResetChat = () => {
    setMessages([]);
  };

  return (
    <AppLayout activeModel={activeModel} onSelectModel={setActiveModel}>
      <div className="h-full flex flex-col justify-between max-w-3xl mx-auto w-full">
        
        {/* CONDITION 1: EMPTY MESSAGES -> SHOW ONLY CLEAN HOME LANDING PAGE */}
        {messages.length === 0 ? (
          <div className="flex-1 flex flex-col justify-center items-center text-center space-y-6 py-4">
            
            {/* High-Contrast Cat Logo Badge */}
<div className="relative group cursor-pointer">
  {/* Glow blur effect adjusted for light/dark */}
  <div className="absolute -inset-1 rounded-2xl bg-gradient-to-r from-violet-600 via-fuchsia-500 to-amber-500 opacity-40 dark:opacity-70 blur-md group-hover:opacity-100 transition duration-500"></div>
  
  {/* Icon Wrapper: Dark background in light mode ensures yellow/purple icon pops */}
  <div className="relative p-3.5 rounded-2xl bg-slate-900 dark:bg-[#111726] text-amber-400 border border-slate-700 dark:border-slate-800 flex items-center justify-center shadow-lg">
    <Cat className="h-7 w-7 stroke-[2.2]" />
  </div>
</div>
            {/* Clean Header */}
            <div className="space-y-2 flex flex-col items-center text-center w-full max-w-lg mx-auto">
              <h1 className="text-xl md:text-2xl font-bold tracking-tight text-center leading-snug">
                How can <span className="bg-gradient-to-r from-violet-500 via-fuchsia-500 to-amber-500 bg-clip-text text-transparent font-extrabold">Echo Cat</span> assist you today?
              </h1>
              <p className="text-[var(--text-muted)] text-xs md:text-sm font-normal text-center leading-relaxed max-w-md">
                Select an AI engine above or click a prompt card below to start.
              </p>
            </div>

            {/* 4 Prompt Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 w-full pt-1">
              {suggestions.map((card, i) => {
                const Icon = card.icon;
                return (
                  <button 
                    key={i}
                    onClick={() => handleSendMessage(card.prompt)}
                    className="p-4 rounded-2xl glass-panel hover:border-violet-500/50 hover:scale-[1.01] transition-all text-left group flex flex-col justify-between h-28"
                  >
                    <div className="flex items-center justify-between w-full">
                      <div className="p-1.5 rounded-lg bg-violet-500/10 text-violet-500 group-hover:bg-violet-500 group-hover:text-white transition-colors">
                        <Icon className="h-3.5 w-3.5" />
                      </div>
                      <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-[var(--bg-workspace)] text-[var(--text-muted)] border border-[var(--border-subtle)]">
                        {card.tag}
                      </span>
                    </div>

                    <div>
                      <div className="font-semibold text-xs group-hover:text-violet-500 flex items-center justify-between transition-colors">
                        {card.title}
                        <ArrowRight className="h-3.5 w-3.5 opacity-0 group-hover:opacity-100 transition-all -translate-x-1 group-hover:translate-x-0" />
                      </div>
                      <div className="text-[11px] text-[var(--text-muted)] mt-0.5 line-clamp-1">{card.desc}</div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        ) : (
          /* CONDITION 2: ACTIVE CONVERSATION -> SHOW ONLY CHAT THREAD VIEW */
          <div className="flex-1 flex flex-col h-full overflow-hidden">
            <div className="flex items-center justify-between pb-3 border-b border-[var(--border-subtle)] mb-2">
              <button 
                onClick={handleResetChat}
                className="flex items-center gap-1.5 text-xs font-semibold text-[var(--text-muted)] hover:text-[var(--text-main)] transition-colors px-3 py-1.5 rounded-xl hover:bg-[var(--bg-surface-hover)]"
              >
                <ArrowLeft className="h-4 w-4" />
                <span>← New Chat</span>
              </button>
              <span className="text-xs text-[var(--text-muted)] font-mono">
                Model: <span className="text-violet-400 font-semibold">{activeModel}</span>
              </span>
            </div>

            <ChatTranscript 
              messages={messages} 
              activeModel={activeModel}
            />
          </div>
        )}

        {/* Floating Composer (Always anchored at bottom) */}
        <PromptComposer 
          onSend={handleSendMessage} 
          activeModel={activeModel} 
        />

      </div>
    </AppLayout>
  );
}